version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sample-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: sample_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sample-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sample-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sample.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sample-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  sample-network:
    driver: bridge 
